using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PlayerHUD : MonoBehaviour
{

    public Text ammoCount;
    public Pistol player;
    public string ammoString;

    // Start is called before the first frame update
    void Start()
    {
        player = GetComponentInParent<Pistol>();
    }

    // Update is called once per frame
    void Update()
    {
        // ammoString = player.ammo.ToString() + " / " + player.maxAmmo.ToString();
        ammoCount.text = player.ammo.ToString() + " / " + player.maxAmmo.ToString();
        // ammoCount.text = ammoString;
    }
}
